export const afiliadosMock = [
    {
      id_afiliado: 1,
      ci: "1234567",
      extension: "LP",
      nombre: "Juan",
      paterno: "Pérez",
      materno: "Gómez",
      sexo: "M",
      fecNac: "1980-05-15",
      telefono: 70123456,
      ocupacion: "Comerciante",
      direccion: "Calle Principal #123",
      fecha_afiliacion: "2023-01-10",
      estado: true,
      patentes: ["ABC-123"],
      puesto: "Fila A - Puesto 5",
      rubro: "Verduras"
    },
    {
      id_afiliado: 2,
      ci: "7654321",
      extension: "SC",
      nombre: "María",
      paterno: "López",
      materno: "Rodríguez",
      sexo: "F",
      fecNac: "1975-08-22",
      telefono: 70765432,
      ocupacion: "Artesana",
      direccion: "Av. Comercio #456",
      fecha_afiliacion: "2023-03-15",
      estado: true,
      patentes: ["DEF-456"],
      puesto: "Fila B - Puesto 12",
      rubro: "Artesanías"
    },
    {
      id_afiliado: 3,
      ci: "9876543",
      extension: "CB",
      nombre: "Carlos",
      paterno: "Méndez",
      materno: "Vargas",
      sexo: "M",
      fecNac: "1990-11-30",
      telefono: 70897654,
      ocupacion: "Carnicero",
      direccion: "Mercado Central Local 8",
      fecha_afiliacion: "2024-02-20",
      estado: false,
      patentes: [],
      puesto: "Sin puesto asignado",
      rubro: "Carnes"
    },
    {
      id_afiliado: 4,
      ci: "4567890",
      extension: "LP",
      nombre: "Ana",
      paterno: "Castro",
      materno: "Torrez",
      sexo: "F",
      fecNac: "1988-04-18",
      telefono: 70456789,
      ocupacion: "Florista",
      direccion: "Plaza Flores #89",
      fecha_afiliacion: "2022-11-05",
      estado: true,
      patentes: ["GHI-789", "JKL-012"],
      puesto: "Fila C - Puesto 3",
      rubro: "Flores"
    },
    {
      id_afiliado: 5,
      ci: "2345678",
      extension: "SC",
      nombre: "Roberto",
      paterno: "Sánchez",
      materno: "Fernández",
      sexo: "M",
      fecNac: "1972-12-10",
      telefono: 70234567,
      ocupacion: "Electrodomésticos",
      direccion: "Av. Industrial #567",
      fecha_afiliacion: "2021-07-22",
      estado: true,
      patentes: ["MNO-345"],
      puesto: "Fila D - Puesto 7",
      rubro: "Electrodomésticos"
    }
  ];
